# get all
GET http://localhost:8080/MyBusCompany/api/buses

###
# Invalid create (Volv isn't a valid brand)
POST http://localhost:8080/MyBusCompany/api/buses
Content-Type: application/json

{
  "registration": "BA-323-BE",
  "brand": "Volv",
  "capacity": 80,
  "kilometers": 1000,
  "releaseYear": "2010-01-01"
}

###
# Invalid create (ba-323-BE is not a valid registration)
POST http://localhost:8080/MyBusCompany/api/buses
Content-Type: application/json

{
  "registration": "Ba-323-BE",
  "brand": "Volvo",
  "capacity": 80,
  "kilometers": 1000,
  "releaseYear": "2010-01-01"
}

###
# Should create a bus
POST http://localhost:8080/MyBusCompany/api/buses
Content-Type: application/json

{
  "registration": "BA-323-BE",
  "brand": "Volvo",
  "capacity": 80,
  "kilometers": 1000,
  "releaseYear": "2010-01-01"
}

> {%
client.global.set("lastId", response.body.id);
%}

###
# should return 409 (ressource already exist)
POST http://localhost:8080/MyBusCompany/api/buses
Content-Type: application/json

{
  "registration": "BA-323-BE",
  "brand": "Volvo",
  "capacity": 80,
  "kilometers": 1000,
  "releaseYear": "2010-01-01"
}

###
# get bus created
GET http://localhost:8080/MyBusCompany/api/buses/{{lastId}}

###
# Error should return 404
GET http://localhost:8080/MyBusCompany/api/buses/404

###
# update
PUT http://localhost:8080/MyBusCompany/api/buses/{{lastId}}
Content-Type: application/json

{
  "registration": "BA-323-BE",
  "brand": "Volvo",
  "capacity": 80,
  "kilometers": 1000,
  "releaseYear": "2010-01-01"
}

###
# Error shoudl return 400
PUT http://localhost:8080/MyBusCompany/api/buses/{{lastId}}
Content-Type: application/json

{
  "dereredde": "tata"
}

###
# Error should return 404
PUT http://localhost:8080/MyBusCompany/api/buses/404
Content-Type: application/json

{
  "name": "tttxtxtt"
}

###
# should delete element
DELETE http://localhost:8080/MyBusCompany/api/buses/{{lastId}}

###
# Error should return 404
DELETE http://localhost:8080/MyBusCompany/api/buses/404

###