# get all
GET http://localhost:8080/MyBusCompany/api/lines

###
# create line 1, should return 201
POST http://localhost:8080/MyBusCompany/api/lines
Content-Type: application/json

{
  "number": 1
}

> {%
client.global.set("lastId", response.body.id);
%}

###
# should return 409 (ressource already exist)
POST http://localhost:8080/MyBusCompany/api/lines
Content-Type: application/json

{
  "number": 1
}

###
# get line created
GET http://localhost:8080/MyBusCompany/api/lines/{{lastId}}

###
# Error should return 404
GET http://localhost:8080/MyBusCompany/api/lines/404

###
# update
PUT http://localhost:8080/MyBusCompany/api/lines/{{lastId}}
Content-Type: application/json

{
  "number": 2
}

###
# Error shoudl return 400
PUT http://localhost:8080/MyBusCompany/api/lines/{{lastId}}
Content-Type: application/json

{
  "number": "tata"
}

###
# Error should return 404
PUT http://localhost:8080/MyBusCompany/api/lines/404
Content-Type: application/json

{
  "number": 2
}

###
# should delete element
DELETE http://localhost:8080/MyBusCompany/api/lines/{{lastId}}

###
# Error should return 404
DELETE http://localhost:8080/MyBusCompany/api/lines/404

###